spring:
  application:
    name: activity-service   # Important for Config Server later


    server:
      port: 8083

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange:
    name: activity.exchange     # Matches ${rabbitmq.exchange.name}
  routingkey:
    activity: activity.created   # Matches ${rabbitmq.routingkey.activity}
  queue:
    name: activity.queue
  routing:
    key: activity.created