server:
  port: 8081

spring:
  application:
#   name: activityservice
    name: activity-service
   data:
     mongodb:
#       uri: mongodb://localhost:27017/fitnessactivity #or whatever one is actually used
       uri: mongodb://localhost:27017/fitnessactivity
       database: fitnessactiivity

    server:
      port: 8082

    eureka:
      cleint:
#        serviceUrl:
        service-url:
          defaultZone: http://localhost:8761/eureka/

