server:
  port: 8080

spring:
  application:
    name: ai-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessreccomendation
      database: fitnessreccomendation

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Custom RabbitMQ configuration (for queue, exchange, routing key)
rabbitmq:
  queue:
    name: activity.queue
  exchange:
    name: fitness.exchange
  routing:
    key: activity.tracking

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#gemini:
#  api:
#    url: ${GEMINI_API_URL}
#    key: ${GEMINI_API_KEY}

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models
    key: AIzaSyAIzaSyD_KjnsWrc6dsGB8mf9I-_NdRPWE-2OTbg