server:
  port: 8084

spring:
  application:
    name: ai-service

  rabbitmq:
    queue:
      name: activity-queue
    exchange:
      name: fitness-exchange
    routing:
      key: activity.created
